services:
  stun-server:
    image: coturn/coturn:4.6
    network_mode: host

  app:
    build: .
    devices:
      - /dev/video0
    volumes:
      - ./certs:/certs
    image: rover-remote-control
    network_mode: host
