services:
  stun-server:
    image: coturn/coturn:4.6
    network_mode: host
    restart: unless-stopped

  app:
    build: .
    image: rover-remote-control
    devices:
      - /dev/video0
    volumes:
      - ./certs:/certs
    network_mode: host
    restart: unless-stopped
