services:
  stun-server:
    image: coturn/coturn:4.6
    network_mode: host
    restart: unless-stopped

  app:
    build: .
    image: rover-remote-control
    devices:
      - /dev/video0
    volumes:
      - ./certs:/certs
    network_mode: host
    command:
      - --cert-file=/certs/cert.crt
      - --key-file=/certs/key.key
      #- --no-control

    # Required for CAN access
    privileged: true

    restart: unless-stopped
